// scr/app/layout.tsx

import React from 'react';
import Navbar from '../components/navbar';
import '../app/global.css'; 
import { getServerSession } from 'next-auth/next';
import { options } from "./api/auth/[...nextauth]/options";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(options);
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
      <Navbar session={session}  />
        {children}
      </body>
    </html>
  );
}
